### ISSUE TITLE
Obsolete Dependency Syntax in metadata.rb

### ISSUE THREAD

**Issue by fr33l** [sous-chefs/varnish#147]
### Cookbook version
3.3.0

### Chef-client version
12.20.3

### Platform Details
Ubuntu 14.04

### Scenario:
Trying to upload varnish cookbook 3.3.0 instead of 2.4.0

### Steps to Reproduce:
knife upload --freeze varnish

### Expected Result:
cookbook uploaded to chef-server

### Actual Result:
```
ERROR: Chef::Exceptions::ObsoleteDependencySyntax: The dependency specification syntax you are using is no longer valid. You may not
specify more than one version constraint for a particular cookbook.
Consult https://docs.chef.io/config_rb_metadata.html for the updated syntax.

Called by: depends 'yum', ">= 3.0", "< 4.1"
Called from:
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/cookbook/metadata.rb:311:in `depends'
  /var/lib/jenkins/jobs/infrastructure-chef/workspace/external-cookbooks/varnish/metadata.rb:21:in `from_file'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/mixin/from_file.rb:30:in `instance_eval'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/mixin/from_file.rb:30:in `from_file'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/cookbook/cookbook_version_loader.rb:308:in `apply_ruby_metadata'
>> Failure.

```
I don't see  any  problems so far why it can't be just  `depends 'yum', '>= 3.0'`

**Comment by RyanJarv** [comment]
Thanks for the issue report!

> I don't see any problems so far why it can't be just depends 'yum', '>= 3.0'

Agreed, not finding any mention of why this exists in the first place so assuming there's no issues after 4.1 we can get this updated.
